# Generated by Django 4.0.10 on 2023-12-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_alta',
        ),
        migrations.AddField(
            model_name='reserva',
            name='confirma',
            field=models.BooleanField(default=False),
        ),
    ]
