# Generated by Django 4.0.10 on 2023-12-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_reserva', '0002_remove_reserva_cantidad_remove_reserva_fecha_alta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_efectiva',
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='horario_reserva',
            field=models.TextField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='reserva',
            name='modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='comentario',
            field=models.TextField(null=True),
        ),
    ]
