version: "3.9"

services:
  web:
    build: .
    command: python /base/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/base
    ports:
    - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  postgres_data: